"""Initial migrations

Revision ID: 8fc34cf86b70
Revises: 0d29dd0c3aef
Create Date: 2020-11-19 00:34:45.319409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc34cf86b70'
down_revision = '0d29dd0c3aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Register', schema=None) as batch_op:
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###
