"""Initial migrations

Revision ID: 9a8e4d06661a
Revises: 8fc34cf86b70
Create Date: 2020-11-19 00:36:20.549502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8e4d06661a'
down_revision = '8fc34cf86b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Register', schema=None) as batch_op:
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.VARCHAR(length=30), nullable=True))

    # ### end Alembic commands ###
