"""Initial migrations

Revision ID: e64dfa75e4c0
Revises: 9a8e4d06661a
Create Date: 2020-11-19 01:10:35.005913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64dfa75e4c0'
down_revision = '9a8e4d06661a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Register', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
